# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.api_error_response import ApiErrorResponse


class UnauthorizedError(ApiError):
    def __init__(self, body: ApiErrorResponse):
        super().__init__(status_code=401, body=body)
