# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .currency_code import CurrencyCode


class Amount(UniversalBaseModel):
    """
    Model for amount
    """

    amount_value: typing_extensions.Annotated[float, FieldMetadata(alias="amountValue")] = pydantic.Field()
    """
    Numerical value of the transaction
    """

    amount_currency: typing_extensions.Annotated[CurrencyCode, FieldMetadata(alias="amountCurrency")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
