# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .risk_level import RiskLevel
from .tag import Tag


class BlockchainRiskCategory(UniversalBaseModel):
    """
    Category of the blockchain risk
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the risk category
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable name of the risk category
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the risk category
    """

    tags: typing.Optional[typing.List[Tag]] = pydantic.Field(default=None)
    """
    Additional information that can be added via tags
    """

    risk_score: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="riskScore")] = pydantic.Field(
        default=None
    )
    """
    Numeric risk score for this category
    """

    risk_level: typing_extensions.Annotated[typing.Optional[RiskLevel], FieldMetadata(alias="riskLevel")] = (
        pydantic.Field(default=None)
    )
    """
    Risk level of this category
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
