# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .blockchain_counterparty import BlockchainCounterparty
from .blockchain_risk_detail import BlockchainRiskDetail
from .blockchain_risk_subject import BlockchainRiskSubject
from .risk_level import RiskLevel
from .tag import Tag


class BlockchainRisk(UniversalBaseModel):
    """
    Blockchain-specific risk analysis from a provider including risk assessment and counterparty information
    """

    provider: typing.Optional[str] = pydantic.Field(default=None)
    """
    Risk analysis provider (e.g., chainalysis)
    """

    timestamp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Unix timestamp of when the risk analysis was performed
    """

    risk_level: typing_extensions.Annotated[typing.Optional[RiskLevel], FieldMetadata(alias="riskLevel")] = (
        pydantic.Field(default=None)
    )
    """
    Overall risk level of the transaction
    """

    risk_score: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="riskScore")] = pydantic.Field(
        default=None
    )
    """
    Numeric risk score from 0 to 100
    """

    counterparties: typing.Optional[typing.List[BlockchainCounterparty]] = pydantic.Field(default=None)
    """
    List of counterparties involved in the transaction
    """

    subject: typing.Optional[BlockchainRiskSubject] = pydantic.Field(default=None)
    """
    Subject of the risk analysis (address, transaction, entity, or smart contract)
    """

    risks: typing.Optional[typing.List[BlockchainRiskDetail]] = pydantic.Field(default=None)
    """
    Detailed risk categories and their analysis
    """

    tags: typing.Optional[typing.List[Tag]] = pydantic.Field(default=None)
    """
    Additional information that can be added via tags
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
