# This file was auto-generated by Fern from our API Definition.

import typing

BusinessUserSegment = typing.Union[
    typing.Literal["SOLE_PROPRIETORSHIP", "LIMITED", "SMB", "SMALL", "MEDIUM", "LARGE", "UNKNOWN"], typing.Any
]
