# This file was auto-generated by Fern from our API Definition.

import typing

CaseManagementEventCaseStatusReason = typing.Union[
    typing.Literal["FALSE_POSITIVE", "INVESTIGATION_COMPLETED", "DOCUMENTS_COLLECTED", "OTHER"], typing.Any
]
