# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Date(UniversalBaseModel):
    """
    Model for date
    """

    day: float = pydantic.Field()
    """
    Day of date
    """

    month: float = pydantic.Field()
    """
    Month of date
    """

    year: float = pydantic.Field()
    """
    Year of date
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
