# This file was auto-generated by Fern from our API Definition.

import typing

EmploymentStatus = typing.Union[
    typing.Literal[
        "UNEMPLOYED",
        "EMPLOYED",
        "SELF_EMPLOYED",
        "FREELANCER",
        "STUDENT",
        "FULL_TIME",
        "PART_TIME",
        "SOLE_PROPRIETOR",
        "PENSIONER",
        "COMPANY_OWNER",
        "OTHER",
        "NA",
    ],
    typing.Any,
]
