# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .expected_transaction_currency import ExpectedTransactionCurrency


class ExpectedTransactionCurrencies(UniversalBaseModel):
    """
    Model for expected transaction currencies
    """

    incoming: typing.Optional[typing.List[ExpectedTransactionCurrency]] = pydantic.Field(default=None)
    """
    Currencies the user expects to receive transactions in
    """

    outgoing: typing.Optional[typing.List[ExpectedTransactionCurrency]] = pydantic.Field(default=None)
    """
    Currencies the user expects to send transactions to
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
