# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .custom_column import CustomColumn
from .list_metadata_ttl import ListMetadataTtl


class ListMetadata(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    List name
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    List description
    """

    status: typing.Optional[bool] = None
    checksum: typing.Optional[str] = None
    columns: typing.Optional[typing.List[CustomColumn]] = None
    ttl: typing.Optional[ListMetadataTtl] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
