# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ListMetadataTtlUnit(str, enum.Enum):
    HOUR = "HOUR"
    DAY = "DAY"

    def visit(self, hour: typing.Callable[[], T_Result], day: typing.Callable[[], T_Result]) -> T_Result:
        if self is ListMetadataTtlUnit.HOUR:
            return hour()
        if self is ListMetadataTtlUnit.DAY:
            return day()
