# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ListUpdatedDetailsAction(str, enum.Enum):
    SET = "SET"
    UNSET = "UNSET"
    CLEAR = "CLEAR"

    def visit(
        self,
        set_: typing.Callable[[], T_Result],
        unset: typing.Callable[[], T_Result],
        clear: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ListUpdatedDetailsAction.SET:
            return set_()
        if self is ListUpdatedDetailsAction.UNSET:
            return unset()
        if self is ListUpdatedDetailsAction.CLEAR:
            return clear()
