# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_header import ListHeader
from .list_item import ListItem


class ListExisted(UniversalBaseModel):
    """
    List with ID and header
    """

    list_id: typing_extensions.Annotated[str, FieldMetadata(alias="listId")]
    header: ListHeader
    items: typing.List[ListItem] = pydantic.Field()
    """
    List items
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
