# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class MartialStatus(str, enum.Enum):
    """
    Martial status of the individual
    """

    DIVORCED = "DIVORCED"
    MARRIED = "MARRIED"
    SINGLE = "SINGLE"
    WIDOWED = "WIDOWED"
    NA = "NA"

    def visit(
        self,
        divorced: typing.Callable[[], T_Result],
        married: typing.Callable[[], T_Result],
        single: typing.Callable[[], T_Result],
        widowed: typing.Callable[[], T_Result],
        na: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is MartialStatus.DIVORCED:
            return divorced()
        if self is MartialStatus.MARRIED:
            return married()
        if self is MartialStatus.SINGLE:
            return single()
        if self is MartialStatus.WIDOWED:
            return widowed()
        if self is MartialStatus.NA:
            return na()
