# This file was auto-generated by Fern from our API Definition.

import typing

PaymentMethod = typing.Union[
    typing.Literal[
        "ACH", "CARD", "IBAN", "UPI", "GENERIC_BANK_ACCOUNT", "MPESA", "SWIFT", "WALLET", "CHECK", "CASH", "NPP"
    ],
    typing.Any,
]
