# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PepRank(str, enum.Enum):
    """
    PEP rank
    """

    LEVEL_1 = "LEVEL_1"
    LEVEL_2 = "LEVEL_2"
    LEVEL_3 = "LEVEL_3"

    def visit(
        self,
        level_1: typing.Callable[[], T_Result],
        level_2: typing.Callable[[], T_Result],
        level_3: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PepRank.LEVEL_1:
            return level_1()
        if self is PepRank.LEVEL_2:
            return level_2()
        if self is PepRank.LEVEL_3:
            return level_3()
