# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .file_info import FileInfo


class PersonAttachment(UniversalBaseModel):
    """
    PersonAttachment model generalizes User's uploaded attachments
    """

    id: typing.Optional[str] = None
    comment: typing.Optional[str] = pydantic.Field(default=None)
    """
    User's comment on the attached file.
    """

    files: typing.List[FileInfo]
    user_id: typing_extensions.Annotated[str, FieldMetadata(alias="userId")]
    created_at: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="createdAt")] = None
    deleted_at: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="deletedAt")] = None
    tags: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
