# This file was auto-generated by Fern from our API Definition.

import typing

RuleLabels = typing.Union[
    typing.Literal[
        "UNEXPECTED_BEHAVIOR",
        "ILLICIT_GAINS_CHECK",
        "RFI_TRIGGER",
        "EDD_TRIGGER",
        "KYC_TRIGGER",
        "SCAM",
        "ABUSE",
        "ACCOUNT_TAKEOVER",
        "DISPUTE",
        "SANCTIONS",
        "SANCTIONS_PEP",
        "SANCTIONS_PEP_ADVERSE_MEDIA",
        "SANCTIONS_MANUAL_REVIEW",
    ],
    typing.Any,
]
