# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class SanctionsScreeningEntity(str, enum.Enum):
    USER = "USER"
    BANK = "BANK"
    IBAN = "IBAN"
    EXTERNAL_USER = "EXTERNAL_USER"

    def visit(
        self,
        user: typing.Callable[[], T_Result],
        bank: typing.Callable[[], T_Result],
        iban: typing.Callable[[], T_Result],
        external_user: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is SanctionsScreeningEntity.USER:
            return user()
        if self is SanctionsScreeningEntity.BANK:
            return bank()
        if self is SanctionsScreeningEntity.IBAN:
            return iban()
        if self is SanctionsScreeningEntity.EXTERNAL_USER:
            return external_user()
