# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .sar_report_status import SarReportStatus


class SarWebhookDetails(UniversalBaseModel):
    """
    Payload sent for SAR lifecycle webhook events (SAR_CREATED, SAR_SUBMITTED, SAR_SUBMISSION_ACCEPTED).
    """

    report_id: typing_extensions.Annotated[str, FieldMetadata(alias="reportId")] = pydantic.Field()
    """
    Unique identifier of the SAR report
    """

    status: SarReportStatus
    user_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="userId")] = pydantic.Field(
        default=None
    )
    """
    ID of the subject user the SAR is filed against, if any
    """

    case_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="caseId")] = pydantic.Field(
        default=None
    )
    """
    ID of the case the SAR is associated with, if any
    """

    created_at: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="createdAt")] = pydantic.Field(
        default=None
    )
    """
    Timestamp at which the SAR was created. Measured in ms since the Unix epoch.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
