# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .sar_message_attachment import SarMessageAttachment


class SarMessageReceivedDetails(UniversalBaseModel):
    """
    Payload sent when an inbound message is received from a regulator or FIU on a previously submitted SAR.
    """

    report_id: typing_extensions.Annotated[str, FieldMetadata(alias="reportId")] = pydantic.Field()
    """
    Unique identifier of the SAR report the message is associated with
    """

    message_id: typing_extensions.Annotated[str, FieldMetadata(alias="messageId")] = pydantic.Field()
    """
    Unique identifier of the inbound message
    """

    sender: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name or identifier of the regulator/FIU that sent the message
    """

    subject: typing.Optional[str] = None
    body: typing.Optional[str] = None
    received_at: typing_extensions.Annotated[float, FieldMetadata(alias="receivedAt")] = pydantic.Field()
    """
    Timestamp at which the message was received. Measured in ms since the Unix epoch.
    """

    attachments: typing.Optional[typing.List[SarMessageAttachment]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
