# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class Tag(UniversalBaseModel):
    """
    Generic key-value pair model to append a custom variable being sent to Flagright API
    """

    key: str = pydantic.Field()
    """
    Key value when you are creating a custom variable
    """

    value: str = pydantic.Field()
    """
    Value for a given key when you are creating a custom variable
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
