# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .country_code import CountryCode


class TaxIdentification(UniversalBaseModel):
    """
    Tax identification information for a specific country
    """

    country: CountryCode
    tax_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="taxId")] = pydantic.Field(
        default=None
    )
    """
    Tax identification number for the country
    """

    declaration_date: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="declarationDate")] = (
        pydantic.Field(default=None)
    )
    """
    Date when the tax identification was declared or registered
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
