# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rule_action import RuleAction


class TransactionStatusDetails(UniversalBaseModel):
    transaction_id: typing_extensions.Annotated[str, FieldMetadata(alias="transactionId")]
    reasons: typing.List[str]
    status: RuleAction
    comment: typing.Optional[str] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type of transaction (ex: DEPOSIT, WITHDRAWAL, TRANSFER, EXTERNAL_PAYMENT, REFUND, OTHER)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
