# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class UserDetailsGender(str, enum.Enum):
    """
    Gender of the individual - Male, Female or Non-Binary
    """

    M = "M"
    F = "F"
    NB = "NB"

    def visit(
        self, m: typing.Callable[[], T_Result], f: typing.Callable[[], T_Result], nb: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is UserDetailsGender.M:
            return m()
        if self is UserDetailsGender.F:
            return f()
        if self is UserDetailsGender.NB:
            return nb()
