# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class WalletNetwork(str, enum.Enum):
    """
    Network of the wallet
    """

    BITCOIN = "BITCOIN"
    ETHEREUM = "ETHEREUM"
    POLYGON = "POLYGON"
    BNB_SMART_CHAIN = "BNB_SMART_CHAIN"
    BNB_BEACON_CHAIN = "BNB_BEACON_CHAIN"
    ARBITRUM_L_2 = "ARBITRUM_L2"
    SOLANA = "SOLANA"
    AVALANCHE_C_CHAIN = "AVALANCHE_C_CHAIN"
    LITECOIN = "LITECOIN"
    BITCOIN_CASH = "BITCOIN_CASH"
    RIPPLE = "RIPPLE"
    STELLAR = "STELLAR"
    EOS_PUBLIC = "EOS_PUBLIC"
    TRON = "TRON"
    CARDANO = "CARDANO"
    POLKADOT = "POLKADOT"
    NEAR_PROTOCOL = "NEAR_PROTOCOL"
    COSMOS = "COSMOS"
    DOGECOIN = "DOGECOIN"
    OPTIMISM_MAINNET = "OPTIMISM_MAINNET"
    FANTOM = "FANTOM"
    HEDERA = "HEDERA"
    ALGORAND = "ALGORAND"
    CELESTIA = "CELESTIA"

    def visit(
        self,
        bitcoin: typing.Callable[[], T_Result],
        ethereum: typing.Callable[[], T_Result],
        polygon: typing.Callable[[], T_Result],
        bnb_smart_chain: typing.Callable[[], T_Result],
        bnb_beacon_chain: typing.Callable[[], T_Result],
        arbitrum_l_2: typing.Callable[[], T_Result],
        solana: typing.Callable[[], T_Result],
        avalanche_c_chain: typing.Callable[[], T_Result],
        litecoin: typing.Callable[[], T_Result],
        bitcoin_cash: typing.Callable[[], T_Result],
        ripple: typing.Callable[[], T_Result],
        stellar: typing.Callable[[], T_Result],
        eos_public: typing.Callable[[], T_Result],
        tron: typing.Callable[[], T_Result],
        cardano: typing.Callable[[], T_Result],
        polkadot: typing.Callable[[], T_Result],
        near_protocol: typing.Callable[[], T_Result],
        cosmos: typing.Callable[[], T_Result],
        dogecoin: typing.Callable[[], T_Result],
        optimism_mainnet: typing.Callable[[], T_Result],
        fantom: typing.Callable[[], T_Result],
        hedera: typing.Callable[[], T_Result],
        algorand: typing.Callable[[], T_Result],
        celestia: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is WalletNetwork.BITCOIN:
            return bitcoin()
        if self is WalletNetwork.ETHEREUM:
            return ethereum()
        if self is WalletNetwork.POLYGON:
            return polygon()
        if self is WalletNetwork.BNB_SMART_CHAIN:
            return bnb_smart_chain()
        if self is WalletNetwork.BNB_BEACON_CHAIN:
            return bnb_beacon_chain()
        if self is WalletNetwork.ARBITRUM_L_2:
            return arbitrum_l_2()
        if self is WalletNetwork.SOLANA:
            return solana()
        if self is WalletNetwork.AVALANCHE_C_CHAIN:
            return avalanche_c_chain()
        if self is WalletNetwork.LITECOIN:
            return litecoin()
        if self is WalletNetwork.BITCOIN_CASH:
            return bitcoin_cash()
        if self is WalletNetwork.RIPPLE:
            return ripple()
        if self is WalletNetwork.STELLAR:
            return stellar()
        if self is WalletNetwork.EOS_PUBLIC:
            return eos_public()
        if self is WalletNetwork.TRON:
            return tron()
        if self is WalletNetwork.CARDANO:
            return cardano()
        if self is WalletNetwork.POLKADOT:
            return polkadot()
        if self is WalletNetwork.NEAR_PROTOCOL:
            return near_protocol()
        if self is WalletNetwork.COSMOS:
            return cosmos()
        if self is WalletNetwork.DOGECOIN:
            return dogecoin()
        if self is WalletNetwork.OPTIMISM_MAINNET:
            return optimism_mainnet()
        if self is WalletNetwork.FANTOM:
            return fantom()
        if self is WalletNetwork.HEDERA:
            return hedera()
        if self is WalletNetwork.ALGORAND:
            return algorand()
        if self is WalletNetwork.CELESTIA:
            return celestia()
