# This file was auto-generated by Fern from our API Definition.

import typing

from .alert_opened_details import AlertOpenedDetails
from .alert_status_details import AlertStatusDetails
from .case_opened_details import CaseOpenedDetails
from .case_status_details import CaseStatusDetails
from .cra_risk_level_updated_details import CraRiskLevelUpdatedDetails
from .kyc_status_details import KycStatusDetails
from .transaction_status_details import TransactionStatusDetails
from .user_state_details import UserStateDetails
from .user_tags_update import UserTagsUpdate

WebhookEventData = typing.Union[
    UserStateDetails,
    CaseStatusDetails,
    CaseOpenedDetails,
    AlertStatusDetails,
    AlertOpenedDetails,
    TransactionStatusDetails,
    KycStatusDetails,
    UserTagsUpdate,
    CraRiskLevelUpdatedDetails,
]
